query getArticles {
  posts {
    nodes {
      databaseId
      title
      slug
      author {
        node {
          name
        }
      }
      featuredImage {
        node {
          altText
          sourceUrl
        }
      }
    }
  }
}
